{% set name = "cytoolz" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 13a7bf254c3c0d28b12e2290b82aed0f0977a4c2a2bf84854fcdc7796a29f3b0

build:
  number: 1
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir --no-build-isolation -vv --config-settings="--global-option=--with-cython"

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
  host:
    - python
    - cython >=0.29
    - pip
    - setuptools >=77
    - setuptools-git-versioning >=2.0
  run:
    - python
    - toolz >=0.8.0
  run_constrained:
    - cython >=0.29

test:
  imports:
    - cytoolz
    - cytoolz.curried
  requires:
    # Require gcc and cython to run the 'cyntonize' command
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cython
    - pip
    - pytest
    # cythonize requires distutils, which setuptools provides
    - setuptools
  commands:
    - pip check
    # Make sure we can cimport cytoolz
    - echo 'cimport cytoolz ; from cytoolz.functoolz cimport memoize' > try_cimport_cytoolz.pyx  # [not win]
    - cythonize -i try_cimport_cytoolz.pyx  # [not win]
    - python -c 'import try_cimport_cytoolz'  # [not win]
    - pytest -vv --pyargs cytoolz

about:
  home: https://github.com/pytoolz/cytoolz
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Cython implementation of Toolz. High performance functional utilities
  description: |
    CyToolz is the Cython implementation of the toolz package, which provides
    high performance utility functions for iterables, functions, and
    dictionaries.
  doc_url: https://toolz.readthedocs.io
  dev_url: https://github.com/pytoolz/cytoolz

extra:
  recipe-maintainers:
    - eriknw
    - mrocklin
    - jcrist
    - jakirkham
