{% set version = "0.9.0" %}

package:
  name: cytoolz
  version: {{ version }}

source:
  fn: cytoolz-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/c/cytoolz/cytoolz-{{ version }}.tar.gz
  sha256: 5ebb55855a8bb7800afa58e52408763935527e0305f35600c71b43c86013dec2
  patches:
    ########################################################
    # Remove problematic Cython doctests.                  #
    #                                                      #
    # xref: https://github.com/pytoolz/cytoolz/issues/116  #
    ########################################################
    - Drop-test_curried_doctests.patch

build:
  number: 0
  script: python setup.py install --no-cython --single-version-externally-managed --record=record.txt

requirements:
  build:
    - setuptools
    - python
    - toolz >=0.8.0
  run:
    - python
    - toolz >=0.8.0

test:
  requires:
    - nose
    - toolz 0.8.2
  imports:
    - cytoolz
    - cytoolz.curried
  commands:
    - nosetests --with-doctest cytoolz

about:
  home: https://github.com/pytoolz/cytoolz
  license: BSD 3-Clause
  summary: Cython implementation of Toolz. High performance functional utilities.

extra:
  recipe-maintainers:
    - eriknw
    - mrocklin
    - jcrist
    - jakirkham
