travis:
  secure:
    BINSTAR_TOKEN: VnCUS3nndlOVvmhrgzgiqT1ZJmvZQUuF3y9zfQsOeCogPtAJq5LBsAbu2ElKiURbEa9cOiFdzFNEyn+LaUnuWHaRnNQTny1/l2ThJzq5Df6zeNsdeLvw7ntLSp7hN3NnbETZvZ3rvAMe/YApQ9SWtilz9JmPzBGpzp8kIE3l70VrYGQD4F9e41lZPe5NoTu6ueL6EBChyjM+u0LFGGBKck54ndzdQLzc2xe/aXKhcAqcWXE4pJpKUVnP8hTOuJ+h/0mNXTs+bFAf6naZzWFsmk8gptyVx5BP6k7WxRqLHY6mDGhNQanrXsazFFhnQeFqEZp/qPCTGYofrA4gEmz4ZmrDyZ/gjvJUgHhWTnG3pilBDQyxNTMH4AvQZqdRDNSNh/VkCgtslN6uiMYRZT9cs8db35exLrVjrncnMxliwU+gnSIChhz0dzocl3ayO8bhF/7SE6Mwri4qQpPgaKvShKP2GbnhxYhs6VS53Rdh2SU0znz5EdtBTfhEmmthNn87TkHhVrayZVf6OWWz3+PqUKaVi87GJcZ4kn3e3Q+WNltXVk1OxOr2cRwOrj3r86m0zPqs196mNKCekKqwJMujjYa87ZcOtN4zFPcBoRL5db29HiqC9xUwmV4T6/CDj0ctboH5fYLFWYXAPl1RR17fhROTlDc/Ytoa9kne7zDF0gk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
